export const Theme = {
  colors: {
    background: '#F9F9F8',
    surface: '#F9F9F8',
    surfaceDim: '#DADAD9',
    surfaceBright: '#F9F9F8',
    surfaceLowest: '#FFFFFF',
    surfaceLow: '#F3F4F3',
    surfaceContainer: '#EEEEED',
    surfaceHigh: '#E8E8E7',
    surfaceHighest: '#E2E2E2',
    onSurface: '#1A1C1C',
    onSurfaceVariant: '#3F4947',
    inverseSurface: '#2F3130',
    inverseOnSurface: '#F1F1F0',
    outline: '#6F7977',
    outlineVariant: '#BFC9C6',
    surfaceTint: '#286860',
    primary: '#0D564D',
    onPrimary: '#FFFFFF',
    primaryContainer: '#2E6E65',
    onPrimaryContainer: '#ADEEE2',
    inversePrimary: '#93D2C7',
    secondary: '#9D4223',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#FE8C66',
    onSecondaryContainer: '#742406',
    tertiary: '#644700',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#825D00',
    onTertiaryContainer: '#FFDC9F',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#93000A',
    gold: '#F4C261',
    crisis: '#DC2626',
    textMuted: '#6F7977',
  },
  spacing: {
    base: 4,
    xs: 8,
    sm: 16,
    md: 24,
    lg: 32,
    xl: 48,
    margin: 20,
    gutter: 16,
  },
  fonts: {
    display: 'Sora_700Bold',
    headline: 'Sora_600SemiBold',
    body: 'PlusJakartaSans_400Regular',
    bodyMedium: 'PlusJakartaSans_500Medium',
    bodyBold: 'PlusJakartaSans_700Bold',
  },
  radius: {
    sm: 4,
    default: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  shadows: {
    soft: {
      shadowColor: '#2E6E65',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 20,
      elevation: 3,
    },
    medium: {
      shadowColor: '#2E6E65',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 24,
      elevation: 6,
    },
  }
};
