/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as Meeting_workspaceRouteImport } from './routes/meeting_workspace'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BreatheRouteImport } from './routes/breathe'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AccountDeletedRouteImport } from './routes/account-deleted'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistOnboardingRouteImport } from './routes/therapist/onboarding'
import { Route as TherapistDashboardRouteImport } from './routes/therapist/dashboard'
import { Route as SignUpSsoCallbackRouteImport } from './routes/sign-up/sso-callback'
import { Route as SignInSsoCallbackRouteImport } from './routes/sign-in/sso-callback'
import { Route as SessionBookingIdRouteImport } from './routes/session.$bookingId'
import { Route as OrgOnboardingRouteImport } from './routes/org/onboarding'
import { Route as OrgDashboardRouteImport } from './routes/org/dashboard'
import { Route as BookingTherapistIdRouteImport } from './routes/booking.$therapistId'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ConferencesIdRoomRouteImport } from './routes/conferences_.$id.room'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const Meeting_workspaceRoute = Meeting_workspaceRouteImport.update({
  id: '/meeting_workspace',
  path: '/meeting_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BreatheRoute = BreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletedRoute = AccountDeletedRouteImport.update({
  id: '/account-deleted',
  path: '/account-deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistOnboardingRoute = TherapistOnboardingRouteImport.update({
  id: '/therapist/onboarding',
  path: '/therapist/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistDashboardRoute = TherapistDashboardRouteImport.update({
  id: '/therapist/dashboard',
  path: '/therapist/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSsoCallbackRoute = SignUpSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSsoCallbackRoute = SignInSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignInRoute,
} as any)
const SessionBookingIdRoute = SessionBookingIdRouteImport.update({
  id: '/session/$bookingId',
  path: '/session/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOnboardingRoute = OrgOnboardingRouteImport.update({
  id: '/org/onboarding',
  path: '/org/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgDashboardRoute = OrgDashboardRouteImport.update({
  id: '/org/dashboard',
  path: '/org/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTherapistIdRoute = BookingTherapistIdRouteImport.update({
  id: '/booking/$therapistId',
  path: '/booking/$therapistId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesIdRoomRoute = ConferencesIdRoomRouteImport.update({
  id: '/conferences_/$id/room',
  path: '/conferences/$id/room',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/bookings': typeof BookingsRoute
  '/breathe': typeof BreatheRoute
  '/chat': typeof ChatRoute
  '/conferences': typeof ConferencesRoute
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/journal': typeof JournalRoute
  '/meeting_workspace': typeof Meeting_workspaceRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/booking/$therapistId': typeof BookingTherapistIdRoute
  '/org/dashboard': typeof OrgDashboardRoute
  '/org/onboarding': typeof OrgOnboardingRoute
  '/session/$bookingId': typeof SessionBookingIdRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
  '/therapist/onboarding': typeof TherapistOnboardingRoute
  '/conferences/$id/room': typeof ConferencesIdRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/bookings': typeof BookingsRoute
  '/breathe': typeof BreatheRoute
  '/chat': typeof ChatRoute
  '/conferences': typeof ConferencesRoute
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/journal': typeof JournalRoute
  '/meeting_workspace': typeof Meeting_workspaceRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/booking/$therapistId': typeof BookingTherapistIdRoute
  '/org/dashboard': typeof OrgDashboardRoute
  '/org/onboarding': typeof OrgOnboardingRoute
  '/session/$bookingId': typeof SessionBookingIdRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
  '/therapist/onboarding': typeof TherapistOnboardingRoute
  '/conferences/$id/room': typeof ConferencesIdRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/bookings': typeof BookingsRoute
  '/breathe': typeof BreatheRoute
  '/chat': typeof ChatRoute
  '/conferences': typeof ConferencesRoute
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/journal': typeof JournalRoute
  '/meeting_workspace': typeof Meeting_workspaceRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/booking/$therapistId': typeof BookingTherapistIdRoute
  '/org/dashboard': typeof OrgDashboardRoute
  '/org/onboarding': typeof OrgOnboardingRoute
  '/session/$bookingId': typeof SessionBookingIdRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
  '/therapist/onboarding': typeof TherapistOnboardingRoute
  '/conferences_/$id/room': typeof ConferencesIdRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account-deleted'
    | '/bookings'
    | '/breathe'
    | '/chat'
    | '/conferences'
    | '/dashboard'
    | '/delete-account'
    | '/journal'
    | '/meeting_workspace'
    | '/mood'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reports'
    | '/sign-in'
    | '/sign-up'
    | '/subscription'
    | '/support'
    | '/terms'
    | '/therapists'
    | '/wallet'
    | '/admin/dashboard'
    | '/booking/$therapistId'
    | '/org/dashboard'
    | '/org/onboarding'
    | '/session/$bookingId'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
    | '/therapist/dashboard'
    | '/therapist/onboarding'
    | '/conferences/$id/room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account-deleted'
    | '/bookings'
    | '/breathe'
    | '/chat'
    | '/conferences'
    | '/dashboard'
    | '/delete-account'
    | '/journal'
    | '/meeting_workspace'
    | '/mood'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reports'
    | '/sign-in'
    | '/sign-up'
    | '/subscription'
    | '/support'
    | '/terms'
    | '/therapists'
    | '/wallet'
    | '/admin/dashboard'
    | '/booking/$therapistId'
    | '/org/dashboard'
    | '/org/onboarding'
    | '/session/$bookingId'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
    | '/therapist/dashboard'
    | '/therapist/onboarding'
    | '/conferences/$id/room'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account-deleted'
    | '/bookings'
    | '/breathe'
    | '/chat'
    | '/conferences'
    | '/dashboard'
    | '/delete-account'
    | '/journal'
    | '/meeting_workspace'
    | '/mood'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reports'
    | '/sign-in'
    | '/sign-up'
    | '/subscription'
    | '/support'
    | '/terms'
    | '/therapists'
    | '/wallet'
    | '/admin/dashboard'
    | '/booking/$therapistId'
    | '/org/dashboard'
    | '/org/onboarding'
    | '/session/$bookingId'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
    | '/therapist/dashboard'
    | '/therapist/onboarding'
    | '/conferences_/$id/room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountDeletedRoute: typeof AccountDeletedRoute
  BookingsRoute: typeof BookingsRoute
  BreatheRoute: typeof BreatheRoute
  ChatRoute: typeof ChatRoute
  ConferencesRoute: typeof ConferencesRoute
  DashboardRoute: typeof DashboardRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  JournalRoute: typeof JournalRoute
  Meeting_workspaceRoute: typeof Meeting_workspaceRoute
  MoodRoute: typeof MoodRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  SubscriptionRoute: typeof SubscriptionRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TherapistsRoute: typeof TherapistsRoute
  WalletRoute: typeof WalletRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BookingTherapistIdRoute: typeof BookingTherapistIdRoute
  OrgDashboardRoute: typeof OrgDashboardRoute
  OrgOnboardingRoute: typeof OrgOnboardingRoute
  SessionBookingIdRoute: typeof SessionBookingIdRoute
  TherapistDashboardRoute: typeof TherapistDashboardRoute
  TherapistOnboardingRoute: typeof TherapistOnboardingRoute
  ConferencesIdRoomRoute: typeof ConferencesIdRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting_workspace': {
      id: '/meeting_workspace'
      path: '/meeting_workspace'
      fullPath: '/meeting_workspace'
      preLoaderRoute: typeof Meeting_workspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathe': {
      id: '/breathe'
      path: '/breathe'
      fullPath: '/breathe'
      preLoaderRoute: typeof BreatheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deleted': {
      id: '/account-deleted'
      path: '/account-deleted'
      fullPath: '/account-deleted'
      preLoaderRoute: typeof AccountDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist/onboarding': {
      id: '/therapist/onboarding'
      path: '/therapist/onboarding'
      fullPath: '/therapist/onboarding'
      preLoaderRoute: typeof TherapistOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist/dashboard': {
      id: '/therapist/dashboard'
      path: '/therapist/dashboard'
      fullPath: '/therapist/dashboard'
      preLoaderRoute: typeof TherapistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/sso-callback': {
      id: '/sign-up/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-up/sso-callback'
      preLoaderRoute: typeof SignUpSsoCallbackRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/sso-callback': {
      id: '/sign-in/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-in/sso-callback'
      preLoaderRoute: typeof SignInSsoCallbackRouteImport
      parentRoute: typeof SignInRoute
    }
    '/session/$bookingId': {
      id: '/session/$bookingId'
      path: '/session/$bookingId'
      fullPath: '/session/$bookingId'
      preLoaderRoute: typeof SessionBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/onboarding': {
      id: '/org/onboarding'
      path: '/org/onboarding'
      fullPath: '/org/onboarding'
      preLoaderRoute: typeof OrgOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/dashboard': {
      id: '/org/dashboard'
      path: '/org/dashboard'
      fullPath: '/org/dashboard'
      preLoaderRoute: typeof OrgDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$therapistId': {
      id: '/booking/$therapistId'
      path: '/booking/$therapistId'
      fullPath: '/booking/$therapistId'
      preLoaderRoute: typeof BookingTherapistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences_/$id/room': {
      id: '/conferences_/$id/room'
      path: '/conferences/$id/room'
      fullPath: '/conferences/$id/room'
      preLoaderRoute: typeof ConferencesIdRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignInRouteChildren {
  SignInSsoCallbackRoute: typeof SignInSsoCallbackRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSsoCallbackRoute: SignInSsoCallbackRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSsoCallbackRoute: typeof SignUpSsoCallbackRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSsoCallbackRoute: SignUpSsoCallbackRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountDeletedRoute: AccountDeletedRoute,
  BookingsRoute: BookingsRoute,
  BreatheRoute: BreatheRoute,
  ChatRoute: ChatRoute,
  ConferencesRoute: ConferencesRoute,
  DashboardRoute: DashboardRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  JournalRoute: JournalRoute,
  Meeting_workspaceRoute: Meeting_workspaceRoute,
  MoodRoute: MoodRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  SubscriptionRoute: SubscriptionRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TherapistsRoute: TherapistsRoute,
  WalletRoute: WalletRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BookingTherapistIdRoute: BookingTherapistIdRoute,
  OrgDashboardRoute: OrgDashboardRoute,
  OrgOnboardingRoute: OrgOnboardingRoute,
  SessionBookingIdRoute: SessionBookingIdRoute,
  TherapistDashboardRoute: TherapistDashboardRoute,
  TherapistOnboardingRoute: TherapistOnboardingRoute,
  ConferencesIdRoomRoute: ConferencesIdRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
