/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BreatheRouteImport } from './routes/breathe'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistOnboardingRouteImport } from './routes/therapist/onboarding'
import { Route as TherapistDashboardRouteImport } from './routes/therapist/dashboard'
import { Route as SessionBookingIdRouteImport } from './routes/session.$bookingId'
import { Route as OrgOnboardingRouteImport } from './routes/org/onboarding'
import { Route as OrgDashboardRouteImport } from './routes/org/dashboard'
import { Route as BookingTherapistIdRouteImport } from './routes/booking.$therapistId'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BreatheRoute = BreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistOnboardingRoute = TherapistOnboardingRouteImport.update({
  id: '/therapist/onboarding',
  path: '/therapist/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistDashboardRoute = TherapistDashboardRouteImport.update({
  id: '/therapist/dashboard',
  path: '/therapist/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionBookingIdRoute = SessionBookingIdRouteImport.update({
  id: '/session/$bookingId',
  path: '/session/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOnboardingRoute = OrgOnboardingRouteImport.update({
  id: '/org/onboarding',
  path: '/org/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgDashboardRoute = OrgDashboardRouteImport.update({
  id: '/org/dashboard',
  path: '/org/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTherapistIdRoute = BookingTherapistIdRouteImport.update({
  id: '/booking/$therapistId',
  path: '/booking/$therapistId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/breathe': typeof BreatheRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/booking/$therapistId': typeof BookingTherapistIdRoute
  '/org/dashboard': typeof OrgDashboardRoute
  '/org/onboarding': typeof OrgOnboardingRoute
  '/session/$bookingId': typeof SessionBookingIdRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
  '/therapist/onboarding': typeof TherapistOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/breathe': typeof BreatheRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/booking/$therapistId': typeof BookingTherapistIdRoute
  '/org/dashboard': typeof OrgDashboardRoute
  '/org/onboarding': typeof OrgOnboardingRoute
  '/session/$bookingId': typeof SessionBookingIdRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
  '/therapist/onboarding': typeof TherapistOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/breathe': typeof BreatheRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/booking/$therapistId': typeof BookingTherapistIdRoute
  '/org/dashboard': typeof OrgDashboardRoute
  '/org/onboarding': typeof OrgOnboardingRoute
  '/session/$bookingId': typeof SessionBookingIdRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
  '/therapist/onboarding': typeof TherapistOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookings'
    | '/breathe'
    | '/chat'
    | '/dashboard'
    | '/journal'
    | '/mood'
    | '/onboarding'
    | '/privacy'
    | '/reports'
    | '/sign-in'
    | '/subscription'
    | '/support'
    | '/terms'
    | '/therapists'
    | '/wallet'
    | '/admin/dashboard'
    | '/booking/$therapistId'
    | '/org/dashboard'
    | '/org/onboarding'
    | '/session/$bookingId'
    | '/therapist/dashboard'
    | '/therapist/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookings'
    | '/breathe'
    | '/chat'
    | '/dashboard'
    | '/journal'
    | '/mood'
    | '/onboarding'
    | '/privacy'
    | '/reports'
    | '/sign-in'
    | '/subscription'
    | '/support'
    | '/terms'
    | '/therapists'
    | '/wallet'
    | '/admin/dashboard'
    | '/booking/$therapistId'
    | '/org/dashboard'
    | '/org/onboarding'
    | '/session/$bookingId'
    | '/therapist/dashboard'
    | '/therapist/onboarding'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookings'
    | '/breathe'
    | '/chat'
    | '/dashboard'
    | '/journal'
    | '/mood'
    | '/onboarding'
    | '/privacy'
    | '/reports'
    | '/sign-in'
    | '/subscription'
    | '/support'
    | '/terms'
    | '/therapists'
    | '/wallet'
    | '/admin/dashboard'
    | '/booking/$therapistId'
    | '/org/dashboard'
    | '/org/onboarding'
    | '/session/$bookingId'
    | '/therapist/dashboard'
    | '/therapist/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingsRoute: typeof BookingsRoute
  BreatheRoute: typeof BreatheRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  JournalRoute: typeof JournalRoute
  MoodRoute: typeof MoodRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  SignInRoute: typeof SignInRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TherapistsRoute: typeof TherapistsRoute
  WalletRoute: typeof WalletRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BookingTherapistIdRoute: typeof BookingTherapistIdRoute
  OrgDashboardRoute: typeof OrgDashboardRoute
  OrgOnboardingRoute: typeof OrgOnboardingRoute
  SessionBookingIdRoute: typeof SessionBookingIdRoute
  TherapistDashboardRoute: typeof TherapistDashboardRoute
  TherapistOnboardingRoute: typeof TherapistOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathe': {
      id: '/breathe'
      path: '/breathe'
      fullPath: '/breathe'
      preLoaderRoute: typeof BreatheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist/onboarding': {
      id: '/therapist/onboarding'
      path: '/therapist/onboarding'
      fullPath: '/therapist/onboarding'
      preLoaderRoute: typeof TherapistOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist/dashboard': {
      id: '/therapist/dashboard'
      path: '/therapist/dashboard'
      fullPath: '/therapist/dashboard'
      preLoaderRoute: typeof TherapistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$bookingId': {
      id: '/session/$bookingId'
      path: '/session/$bookingId'
      fullPath: '/session/$bookingId'
      preLoaderRoute: typeof SessionBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/onboarding': {
      id: '/org/onboarding'
      path: '/org/onboarding'
      fullPath: '/org/onboarding'
      preLoaderRoute: typeof OrgOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/dashboard': {
      id: '/org/dashboard'
      path: '/org/dashboard'
      fullPath: '/org/dashboard'
      preLoaderRoute: typeof OrgDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$therapistId': {
      id: '/booking/$therapistId'
      path: '/booking/$therapistId'
      fullPath: '/booking/$therapistId'
      preLoaderRoute: typeof BookingTherapistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingsRoute: BookingsRoute,
  BreatheRoute: BreatheRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  JournalRoute: JournalRoute,
  MoodRoute: MoodRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  SignInRoute: SignInRoute,
  SubscriptionRoute: SubscriptionRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TherapistsRoute: TherapistsRoute,
  WalletRoute: WalletRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BookingTherapistIdRoute: BookingTherapistIdRoute,
  OrgDashboardRoute: OrgDashboardRoute,
  OrgOnboardingRoute: OrgOnboardingRoute,
  SessionBookingIdRoute: SessionBookingIdRoute,
  TherapistDashboardRoute: TherapistDashboardRoute,
  TherapistOnboardingRoute: TherapistOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
